[tool.briefcase]
project_name = "Altima USB Installer"
bundle = "com.altimalinux.usbinstaller"
version = "1.0.0"
description = "Install Ventoy and copy Altima Linux ISO to USB"
system_python = false
license = "MIT"
requires = ["requests", "PySide6"]
author = "Altima Linux Team"
author_email = "dev@altimalinux.com"

[tool.briefcase.app.altima_usb_installer]
sources = ["src/altima_usb_installer"]
resources = ["src/altima_usb_installer/altima-logo-100.png"]
support_package = "https://briefcase-support.org/python?platform=linux&version=3.10"
long_description = """
Altima USB Installer installs Ventoy on a USB stick and copies Altima Linux ISO to make it bootable.
"""


