[tool.briefcase]
project_name = "Altima USB Installer"
bundle = "com.altimalinux.usbinstaller"
version = "2.0.8"
description = "Prepare Ventoy and copy Altima Linux ISO to USB"
license = "MIT"
author = "Altima Linux Team"
author_email = "dev@altimalinux.com"

[tool.briefcase.app.altima-usb-installer]
sources = ["src/altima_usb_installer"]
resources = [
    "slide1.png",
    "slide2.png",
    "slide3.png"
]
long_description = """
Altima USB Installer prepares Ventoy on your USB stick, downloads an Altima Linux ISO, copies it, and ejects the USB ready to boot.
"""
