name: Build Windows App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PySide6 requests

      - name: Build executable
        run: |
          pip install pyinstaller
          pyinstaller --noconfirm --onefile --windowed altima-usb-installer-win.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Altima-USB-Installer
          path: dist/altima-usb-installer-win.exe
