name: Build Installers (Windows EXE & Linux AppImage)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycairo PyGObject pyinstaller requests

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed altima-usb-installer-gtk.py
        shell: cmd

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: altima-usb-installer-windows
          path: dist/altima-usb-installer-gtk.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install GTK and PyInstaller
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev gir1.2-gtk-3.0 gir1.2-webkit2-4.0 python3-gi
          python -m pip install --upgrade pip
          pip install pyinstaller pycairo PyGObject requests

      - name: Build Linux AppImage
        run: |
          pyinstaller --noconfirm --onefile --windowed altima-usb-installer-gtk.py
          # Create a dummy AppDir and wrap it as AppImage
          mkdir -p AppDir/usr/bin
          cp dist/altima-usb-installer-gtk AppDir/usr/bin/
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage AppDir Altima-USB-Installer-x86_64.AppImage

      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v3
        with:
          name: altima-usb-installer-linux
          path: Altima-USB-Installer-x86_64.AppImage
