name: Build Windows EXE (v2.1.0)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 requests pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed altima-usb-installer-win.py
        shell: cmd

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: altima-usb-installer-windows
          path: dist/altima-usb-installer-win.exe
